name: Build and deploy site

on:
  # Run on all PRs
  pull_request:
  # Run when a PR is merged into main
  push:
    branches:
      - main

jobs:
  build:
    name: Build and deploy site
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Cache Nix environment
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Use Nix dev shell for subsequent steps
        uses: rrbutani/use-nix-shell-action@v1
        with:
          extraNixOptions: --impure --accept-flake-config
      - name: Download data
        run: just download
        env:
          GH_TOKEN: ${{ github.token }}
          # Skip downloading data when running on a PR
          DUMMY: ${{ github.event_name == 'pull_request' }}
      - name: Code generation
        run: just code_gen
      - name: Run Pre-commit
        run: pre-commit run --all-files
        env:
          # Prevent this action failing when running on the main branch
          SKIP: no-commit-to-branch
      - name: Build
        run: just run
      - name: Upload site to artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: dist
      - name: Deploy site
        uses: actions/deploy-pages@v2
        if: ${{ github.event_name == 'push' }}
